package com.jasmine.springboot.dal.dataobject;

public class TalentInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent_info.publish_time
     *
     * @mbg.generated
     */
    private String publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent_info.origin_type
     *
     * @mbg.generated
     */
    private String originType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent_info.article_title
     *
     * @mbg.generated
     */
    private String articleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent_info.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent_info.id
     *
     * @return the value of talent_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent_info.id
     *
     * @param id the value for talent_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent_info.publish_time
     *
     * @return the value of talent_info.publish_time
     *
     * @mbg.generated
     */
    public String getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent_info.publish_time
     *
     * @param publishTime the value for talent_info.publish_time
     *
     * @mbg.generated
     */
    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime == null ? null : publishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent_info.origin_type
     *
     * @return the value of talent_info.origin_type
     *
     * @mbg.generated
     */
    public String getOriginType() {
        return originType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent_info.origin_type
     *
     * @param originType the value for talent_info.origin_type
     *
     * @mbg.generated
     */
    public void setOriginType(String originType) {
        this.originType = originType == null ? null : originType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent_info.article_title
     *
     * @return the value of talent_info.article_title
     *
     * @mbg.generated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent_info.article_title
     *
     * @param articleTitle the value for talent_info.article_title
     *
     * @mbg.generated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent_info.url
     *
     * @return the value of talent_info.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent_info.url
     *
     * @param url the value for talent_info.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}