package com.jasmine.springboot.dal.daointerface;

import com.jasmine.springboot.dal.dataobject.TalentInfo;

public interface TalentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_info
     *
     * @mbg.generated
     */
    int insert(TalentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_info
     *
     * @mbg.generated
     */
    int insertSelective(TalentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_info
     *
     * @mbg.generated
     */
    TalentInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TalentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TalentInfo record);
}